import type { Metadata } from "next";
import NavComponent from '../components/Nav';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import { UserProvider } from "@/app/context/UserContext"; 
import { WordProvider } from "@/app/context/WordContext"; 
import GlobalListener  from "@/components/GlobalListener"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
           <WordProvider>
              <GlobalListener />
              <NavComponent />
              {children}
            </WordProvider>
        </UserProvider>
      </body>
    </html>
  );
}
